# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
        API_IMAGE_NAME: bloodloop-api
        AZURE_WEBAPP_API_NAME: bloodloop-api-dev

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0
    
    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AZURE_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.API_IMAGE_NAME }}:${{ github.sha }}
    
    - name: 'Deploy'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_API_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        images: ${{ secrets.AZURE_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.API_IMAGE_NAME }}:${{ github.sha }}
